const items = [
  {
    "user_id": "admin",
    "section": "lab",
    "name": "% Transferrin saturation",
    "category": "철분",
    "unit": "%",
    "refMin": 15,
    "optMin": 20,
    "optMax": 35,
    "refMax": 50,
    "reference": 1,
    "name_kor": "트랜스페린결합도"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Albumin",
    "category": "단백질",
    "unit": "g/dL",
    "refMin": 3.6,
    "optMin": 4,
    "optMax": 5,
    "refMax": 5.1,
    "reference": 1,
    "name_kor": "알부민",
    "alertMin": 3,
    "alertMax": 5,
    "alertMessage": "3 g/dL 미만이면서 무력감과 피로 등의 증상이 나타나는 경우, 또는 5 g/dL 이상이면서 탈수와 신경계 증상이 나타나는 경우에는 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Albumin/Globulin Ratio",
    "category": "단백질",
    "unit": "ratio",
    "refMin": 1,
    "optMin": 1.4,
    "optMax": 2.1,
    "refMax": 2.5,
    "reference": 1,
    "name_kor": "알부민/글로불린 비율"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Alk Phos",
    "category": "간기능",
    "unit": "IU/L",
    "refMin": 35,
    "optMin": 70,
    "optMax": 100,
    "refMax": 115,
    "reference": 1,
    "name_kor": "알칼리 인산분해효소",
    "description": "GGT와 동반상승하면서 무력감, 피로, 소화불량 등의 증상이 나타나는 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "ALT (SGPT)",
    "category": "간기능",
    "unit": "IU/L",
    "refMin": 6,
    "optMin": 10,
    "optMax": 26,
    "refMax": 29,
    "reference": 1,
    "name_kor": "알라닌아미노전이효소",
    "alertMax": 200,
    "alertMessage": "200 IU/L 이상이면서 피로와 소화불량 등의 증상이 나타나는 경우, 상급의료기관 진료를 권고합니다. 300 IU/L 이상인 경우, 응급 진료가 필요합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Anion gap",
    "category": "대사",
    "unit": "mEq/L",
    "refMin": 6,
    "optMin": 7,
    "optMax": 12,
    "refMax": 16,
    "reference": 1,
    "name_kor": "음이온차"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "AST (SGOT)",
    "category": "간기능",
    "unit": "IU/L",
    "refMin": 10,
    "optMin": 10,
    "optMax": 26,
    "refMax": 35,
    "reference": 1,
    "name_kor": "아스파테이트아미노전이효소",
    "alertMax": 200,
    "alertMessage": "200 IU/L 이상이면서 피로와 소화불량 등의 증상이 나타나는 경우, 상급의료기관 진료를 권고합니다. 300 IU/L 이상인 경우, 응급 진료가 필요합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Bands",
    "category": "백혈구",
    "unit": "%",
    "refMin": 0,
    "optMin": 0,
    "optMax": 5,
    "refMax": 5,
    "reference": 1,
    "name_kor": "간상구(%)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Basophils",
    "category": "백혈구",
    "unit": "%",
    "refMin": 0,
    "optMin": 0,
    "optMax": 1,
    "refMax": 1,
    "reference": 1,
    "name_kor": "호염구(%)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Bilirubin - Direct",
    "category": "간기능",
    "unit": "mg/dL",
    "refMin": 0,
    "optMin": 0,
    "optMax": 0.2,
    "refMax": 0.2,
    "reference": 1,
    "name_kor": "직접빌리루빈",
    "alertMax": 0.4,
    "alertMessage": "0.4 mg/dL 이상이면서 무력감, 피로, 소화불량 등이 나타나는 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Bilirubin - Indirect",
    "category": "간기능",
    "unit": "mg/dL",
    "refMin": 0.2,
    "optMin": 0.1,
    "optMax": 0.7,
    "refMax": 1.2,
    "reference": 1,
    "name_kor": "간접빌리루빈"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Bilirubin - Total",
    "category": "간기능",
    "unit": "mg/dL",
    "refMin": 0.2,
    "optMin": 0.1,
    "optMax": 0.9,
    "refMax": 1.2,
    "reference": 1,
    "name_kor": "총빌리루빈",
    "alertMax": 1.4,
    "alertMessage": "1.4 mg/dL 이상이면서 무력감, 피로, 소화불량 등이 나타나는 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "BUN",
    "category": "신장",
    "unit": "mg/dL",
    "refMin": 7,
    "optMin": 10,
    "optMax": 16,
    "refMax": 25,
    "reference": 1,
    "name_kor": "혈액요소질소",
    "alertMax": 30,
    "alertMessage": "30 mg/dL 이상이면서 피로감을 동반한 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "BUN/Creatinine Ratio",
    "category": "신장",
    "unit": "Ratio",
    "refMin": 6,
    "optMin": 10,
    "optMax": 16,
    "refMax": 22,
    "reference": 1,
    "name_kor": "BUN/크레아틴 비율"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "C-Peptide",
    "category": "혈당",
    "unit": "ng/mL",
    "refMin": 0.8,
    "optMin": 1.1,
    "optMax": 1.6,
    "refMax": 3.1,
    "reference": 1,
    "name_kor": "C펩타이드"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "C-Reactive Protein",
    "category": "염증",
    "unit": "mg/L",
    "refMin": 0,
    "optMin": 0,
    "optMax": 4.5,
    "refMax": 7.9,
    "reference": 1,
    "name_kor": "C반응단백"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Calcium",
    "category": "무기질",
    "unit": "mg/dL",
    "refMin": 8.6,
    "optMin": 9.2,
    "optMax": 10,
    "refMax": 10.4,
    "reference": 1,
    "name_kor": "칼슘"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Calcium/Albumin Ratio",
    "category": "무기질",
    "unit": "ratio",
    "refMin": 0,
    "optMin": 0,
    "optMax": 2.6,
    "refMax": 2.6,
    "reference": 1,
    "name_kor": "칼슘/알부민 비율"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Calcium/Phosphorus Ratio",
    "category": "무기질",
    "unit": "ratio",
    "refMin": 2.3,
    "optMin": 2.3,
    "optMax": 2.7,
    "refMax": 2.7,
    "reference": 1,
    "name_kor": "칼슘/인 비율"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Chloride",
    "category": "전해질",
    "unit": "mEq/L",
    "refMin": 98,
    "optMin": 100,
    "optMax": 106,
    "refMax": 110,
    "reference": 1,
    "name_kor": "염소"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Cholesterol - Total",
    "category": "지질",
    "unit": "mg/dL",
    "refMin": 125,
    "optMin": 160,
    "optMax": 180,
    "refMax": 200,
    "reference": 1,
    "name_kor": "총콜레스테롤"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Cholesterol/HDL Ratio",
    "category": "지질",
    "unit": "Ratio",
    "refMin": 0,
    "optMin": 0,
    "optMax": 3,
    "refMax": 5,
    "reference": 1,
    "name_kor": "총콜레스테롤/HDL 비율"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "CO2",
    "category": "전해질",
    "unit": "mEq/L",
    "refMin": 19,
    "optMin": 25,
    "optMax": 30,
    "refMax": 30,
    "reference": 1,
    "name_kor": "이산화탄소"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Collagen Cross-Linked NTx",
    "category": "뼈",
    "unit": "nmolBCE/mmolcreat",
    "refMin": 5,
    "optMin": 5,
    "optMax": 79,
    "refMax": 79,
    "reference": 1,
    "name_kor": "골대사표지자"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Cortisol - AM",
    "category": "호르몬",
    "unit": "µg/dL",
    "refMin": 4,
    "optMin": 10,
    "optMax": 15,
    "refMax": 22,
    "reference": 1,
    "name_kor": "스트레스호르몬(오전)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Cortisol - PM",
    "category": "호르몬",
    "unit": "µg/dL",
    "refMin": 3,
    "optMin": 6,
    "optMax": 10,
    "refMax": 17,
    "reference": 1,
    "name_kor": "스트레스호르몬(오후)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Creatine Kinase",
    "category": "근육",
    "unit": "u/l",
    "refMin": 44,
    "optMin": 65,
    "optMax": 135,
    "refMax": 196,
    "reference": 1,
    "name_kor": "크레아틴인산활성효소"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Creatinine",
    "category": "신장",
    "unit": "mg/dL",
    "refMin": 0.4,
    "optMin": 0.8,
    "optMax": 1.1,
    "refMax": 1.5,
    "reference": 1,
    "name_kor": "크레아티닌",
    "alertMax": 1.7,
    "alertMessage": "1.7 mg/dL 이상이면서 피로감을 동반한 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Creatinine Clearance",
    "category": "신장",
    "unit": "g/24hours",
    "refMin": 75,
    "optMin": 85,
    "optMax": 115,
    "refMax": 125,
    "reference": 1,
    "name_kor": "크레아티닌청소율"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "DHEA-S",
    "category": "호르몬",
    "sex": "M",
    "unit": "µg/dL",
    "refMin": 65,
    "optMin": 350,
    "optMax": 490,
    "refMax": 510,
    "reference": 1,
    "name_kor": "부신호르몬"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "DHEA-S",
    "category": "호르몬",
    "sex": "F",
    "unit": "µg/dL",
    "refMin": 18,
    "optMin": 275,
    "optMax": 390,
    "refMax": 390,
    "reference": 1,
    "name_kor": "부신호르몬"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "eGFR Non-Afr. American",
    "category": "신장",
    "unit": "mL/min/1.73m2",
    "refMin": 60,
    "optMin": 90,
    "optMax": 120,
    "refMax": 120,
    "reference": 1,
    "name_kor": "추정사구체여과율",
    "alertMin": 25,
    "alertMessage": "수치가 25 미만이면서 무력감과 피로 증상을 동반한 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Eosinophils",
    "category": "백혈구",
    "unit": "%",
    "refMin": 0,
    "optMin": 0,
    "optMax": 3,
    "refMax": 3,
    "reference": 1,
    "name_kor": "호산구(%)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "ESR",
    "category": "염증",
    "sex": "M",
    "unit": "mm/hr",
    "refMin": 0,
    "optMin": 0,
    "optMax": 5,
    "refMax": 15,
    "reference": 1,
    "name_kor": "적혈구침강속도"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "ESR",
    "category": "염증",
    "sex": "F",
    "unit": "mm/hr",
    "refMin": 0,
    "optMin": 0,
    "optMax": 10,
    "refMax": 20,
    "reference": 1,
    "name_kor": "적혈구침강속도"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Estradiol",
    "category": "호르몬",
    "sex": "M",
    "unit": "pg/mL",
    "refMin": 0,
    "optMin": 20,
    "optMax": 30,
    "refMax": 39,
    "reference": 1,
    "name_kor": "에스트로겐"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Estradiol",
    "category": "호르몬",
    "sex": "F",
    "unit": "pg/mL",
    "refMin": 19,
    "optMin": 150,
    "optMax": 350,
    "refMax": 357,
    "reference": 1,
    "name_kor": "에스트로겐"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Ferritin",
    "category": "철분",
    "unit": "ng/mL",
    "refMin": 10,
    "optMin": 30,
    "optMax": 70,
    "refMax": 232,
    "reference": 1,
    "name_kor": "철단백"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Fibrinogen",
    "category": "염증",
    "unit": "mg/dL",
    "refMin": 175,
    "optMin": 200,
    "optMax": 300,
    "refMax": 425,
    "reference": 1,
    "name_kor": "섬유소원",
    "description": "혈액응고에 관여합니다. 급성기 염증 상태에서 증가합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Folate",
    "category": "비타민",
    "unit": "ng/mL",
    "refMin": 5.5,
    "optMin": 15,
    "optMax": 25,
    "refMax": 27,
    "reference": 1,
    "name_kor": "엽산"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Free T3",
    "category": "갑상선",
    "unit": "pg/mL",
    "refMin": 2.3,
    "optMin": 3,
    "optMax": 3.5,
    "refMax": 4.2,
    "reference": 1,
    "name_kor": "유리T3"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Free T4",
    "category": "갑상선",
    "unit": "ng/dL",
    "refMin": 0.8,
    "optMin": 1,
    "optMax": 1.5,
    "refMax": 1.8,
    "reference": 1,
    "name_kor": "유리T4"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Free Thyroxine Index (T7)",
    "category": "갑상선",
    "unit": "Index",
    "refMin": 1.4,
    "optMin": 1.7,
    "optMax": 4.6,
    "refMax": 3.8,
    "reference": 1,
    "name_kor": "유리T7"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Fructosamine",
    "category": "혈당",
    "unit": "µmol/L",
    "refMin": 190,
    "optMin": 190,
    "optMax": 228,
    "refMax": 270,
    "reference": 1,
    "name_kor": "당화단백"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "FSH",
    "category": "호르몬",
    "sex": "F",
    "unit": "mIU/mL",
    "refMin": 1,
    "optMin": 1,
    "optMax": 100,
    "refMax": 100,
    "reference": "SK",
    "name_kor": "난포자극호르몬"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Gastrin",
    "category": "호르몬",
    "unit": "pg/mL",
    "refMin": 0,
    "optMin": 45,
    "optMax": 90,
    "refMax": 100,
    "reference": 1,
    "name_kor": "가스트린"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "GGT",
    "category": "간기능",
    "unit": "IU/L",
    "refMin": 3,
    "optMin": 10,
    "optMax": 30,
    "refMax": 70,
    "reference": 1,
    "name_kor": "감마글루타밀전이효소",
    "description": "Alk Phos와 동반상승하면서 무력감, 피로, 소화불량 등의 증상이 나타나는 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Globulin - Total",
    "category": "단백질",
    "unit": "g/dL",
    "refMin": 1.9,
    "optMin": 2.4,
    "optMax": 2.8,
    "refMax": 3.7,
    "reference": 1,
    "name_kor": "총글로불린"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Glucose",
    "category": "혈당",
    "unit": "mg/dL",
    "refMin": 65,
    "optMin": 75,
    "optMax": 86,
    "refMax": 99,
    "reference": 1,
    "name_kor": "혈중글루코스"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Granulocytes",
    "category": "백혈구",
    "unit": "%",
    "refMin": 55,
    "optMin": 55,
    "optMax": 60,
    "refMax": 60,
    "reference": "SK",
    "name_kor": "과립구(%)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Granulocytes#",
    "category": "백혈구",
    "unit": "10^3/µL",
    "refMin": 2,
    "optMin": 2,
    "optMax": 5.4,
    "refMax": 5.4,
    "reference": "SK",
    "name_kor": "과립구수"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "HDL Cholesterol",
    "category": "지질",
    "unit": "mg/dL",
    "refMin": 46,
    "optMin": 55,
    "optMax": 70,
    "refMax": 100,
    "reference": 1,
    "name_kor": "고밀도지단백 콜레스테롤"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Hematocrit",
    "category": "혈구",
    "sex": "M",
    "unit": "%",
    "refMin": 38.5,
    "optMin": 40,
    "optMax": 48,
    "refMax": 50,
    "reference": 1,
    "name_kor": "적혈구용적률"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Hematocrit",
    "category": "혈구",
    "sex": "F",
    "unit": "%",
    "refMin": 35,
    "optMin": 37,
    "optMax": 44,
    "refMax": 45,
    "reference": 1,
    "name_kor": "적혈구용적률"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Hemoglobin",
    "category": "혈구",
    "sex": "M",
    "unit": "g/dL",
    "refMin": 13.2,
    "optMin": 14,
    "optMax": 15,
    "refMax": 17.1,
    "reference": 1,
    "name_kor": "혈색소",
    "alertMin": 9,
    "alertMax": 16.5,
    "alertMessage": "9 g/dL 이하이면서 무력감과 안면창백 등의 증상이 나타나는 경우, 또는 9 g/dL 이상인 경우에는 상급의료기관 진료를 권고합니다. 7 g/dL 이하일 경우 응급 진료가 필요합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Hemoglobin",
    "category": "혈구",
    "sex": "F",
    "unit": "g/dL",
    "refMin": 11.7,
    "optMin": 13.5,
    "optMax": 14.5,
    "refMax": 15.5,
    "reference": 1,
    "name_kor": "혈색소",
    "alertMin": 9,
    "alertMax": 16.5,
    "alertMessage": "9 g/dL 이하이면서 무력감과 안면창백 등의 증상이 나타나는 경우, 또는 9 g/dL 이상인 경우에는 상급의료기관 진료를 권고합니다. 7 g/dL 이하일 경우 응급 진료가 필요합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Hemoglobin A1C",
    "category": "혈당",
    "unit": "%",
    "refMin": 0,
    "optMin": 4.5,
    "optMax": 5.5,
    "refMax": 5.7,
    "reference": 1,
    "name_kor": "당화혈색소",
    "alertMax": 6.5,
    "alertMessage": "수치가 6.5 이상이면서 식후 피로감과 혈당조절이상 의심 증상이 나타나는 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Homocysteine",
    "category": "염증",
    "unit": "µmol/L",
    "refMin": 0,
    "optMin": 0,
    "optMax": 7.2,
    "refMax": 10.3,
    "reference": 1,
    "name_kor": "호모시스테인",
    "description": "증가시, 비타민B6, B12, 엽산 부족을 의심할 수 있습니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Hs CRP",
    "category": "염증",
    "sex": "M",
    "unit": "mg/L",
    "refMin": 0,
    "optMin": 0,
    "optMax": 0.6,
    "refMax": 2.9,
    "reference": 1,
    "name_kor": "고감도 C반응단백"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Hs CRP",
    "category": "염증",
    "sex": "F",
    "unit": "mg/L",
    "refMin": 0,
    "optMin": 0,
    "optMax": 1.5,
    "refMax": 2.9,
    "reference": 1,
    "name_kor": "고감도 C반응단백"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Insulin - Fasting",
    "category": "혈당",
    "unit": "µIU/mL",
    "refMin": 2,
    "optMin": 2,
    "optMax": 5,
    "refMax": 19,
    "reference": 1,
    "name_kor": "공복인슐린"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Iron - Serum",
    "category": "철분",
    "unit": "µg/dL",
    "refMin": 40,
    "optMin": 85,
    "optMax": 130,
    "refMax": 160,
    "reference": 1,
    "name_kor": "혈청철분"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Laptin",
    "category": "대사",
    "sex": "F",
    "unit": "ng/mL",
    "refMin": 4.7,
    "optMin": 4.1,
    "optMax": 25,
    "refMax": 23.7,
    "reference": 1,
    "name_kor": "렙틴"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "LDH",
    "category": "간기능",
    "unit": "IU/L",
    "refMin": 120,
    "optMin": 140,
    "optMax": 200,
    "refMax": 250,
    "reference": 1,
    "name_kor": "젖산탈수소효소"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "LDL Cholesterol",
    "category": "지질",
    "unit": "mg/dL",
    "refMin": 0,
    "optMin": 0,
    "optMax": 120,
    "refMax": 130,
    "reference": 1,
    "name_kor": "저밀도지단백 콜레스테롤",
    "alertMax": 190,
    "alertMessage": "190 mg/dL 이상인 경우 상급의료기관 진료를 권고합니다. 특별한 증상이 나타나지 않을 수도 있습니다. "
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Leptin",
    "category": "대사",
    "sex": "M",
    "unit": "ng/mL",
    "refMin": 0.3,
    "optMin": 1.2,
    "optMax": 9.5,
    "refMax": 13.4,
    "reference": 1,
    "name_kor": "렙틴"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "LH",
    "category": "호르몬",
    "sex": "F",
    "unit": "mIU/mL",
    "refMin": 1,
    "optMin": 1,
    "optMax": 100,
    "refMax": 100,
    "reference": "SK",
    "name_kor": "황체형성호르몬"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Lymphocytes",
    "category": "백혈구",
    "unit": "%",
    "refMin": 14,
    "optMin": 24,
    "optMax": 44,
    "refMax": 46,
    "reference": 1,
    "name_kor": "림프구(%)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Lymphocytes#",
    "category": "백혈구",
    "unit": "10^3/µL",
    "refMin": 1.2,
    "optMin": 1.2,
    "optMax": 3.6,
    "refMax": 3.6,
    "reference": "SK",
    "name_kor": "림프구수",
    "alertMin": 1,
    "alertMax": 4,
    "alertMessage": "수치가 1 미만이면서 무력감, 피로 등의 증상이 나타나는 경우에는 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Magnesium",
    "category": "무기질",
    "unit": "mg/dL",
    "refMin": 1.5,
    "optMin": 2.2,
    "optMax": 2.5,
    "refMax": 2.5,
    "reference": 1,
    "name_kor": "마그네슘"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "MCH",
    "category": "혈구",
    "unit": "pg",
    "refMin": 27,
    "optMin": 28,
    "optMax": 31.9,
    "refMax": 33,
    "reference": 1,
    "name_kor": "평균적혈구혈색소"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "MCHC",
    "category": "혈구",
    "unit": "g/dL",
    "refMin": 32,
    "optMin": 32,
    "optMax": 35,
    "refMax": 36,
    "reference": 1,
    "name_kor": "평균적혈구혈색소농도"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "MCV",
    "category": "혈구",
    "unit": "fL",
    "refMin": 80,
    "optMin": 82,
    "optMax": 89.9,
    "refMax": 100,
    "reference": 1,
    "name_kor": "평균적혈구용적"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Monocytes",
    "category": "백혈구",
    "unit": "%",
    "refMin": 4,
    "optMin": 0,
    "optMax": 7,
    "refMax": 13,
    "reference": 1,
    "name_kor": "단핵구(%)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Monocytes#",
    "category": "백혈구",
    "unit": "10^3/µL",
    "refMin": 0.1,
    "optMin": 0.1,
    "optMax": 0.9,
    "refMax": 0.9,
    "reference": "SK",
    "name_kor": "단핵구수"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "MPV",
    "category": "혈구",
    "unit": "fL",
    "refMin": 7.4,
    "optMin": 7.4,
    "optMax": 10.4,
    "refMax": 10.4,
    "reference": "SK",
    "name_kor": "혈소판용적"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Neutrophils",
    "category": "백혈구",
    "unit": "%",
    "refMin": 38,
    "optMin": 40,
    "optMax": 60,
    "refMax": 74,
    "reference": 1,
    "name_kor": "호중구(%)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "non-HDL",
    "category": "지질",
    "unit": "mg/dL",
    "refMin": 50,
    "optMin": 50,
    "optMax": 160,
    "refMax": 160,
    "reference": "SK",
    "name_kor": "비HDL"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "PDW",
    "category": "혈구",
    "unit": "%",
    "refMin": 15.5,
    "optMin": 15.5,
    "optMax": 17.5,
    "refMax": 17.5,
    "reference": "SK",
    "name_kor": "혈소판분포폭"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Phosphorus",
    "category": "무기질",
    "unit": "mg/dL",
    "refMin": 2.5,
    "optMin": 3,
    "optMax": 4,
    "refMax": 4.5,
    "reference": 1,
    "name_kor": "인(P)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Platelet - Large Cell Ratio",
    "category": "혈구",
    "unit": "%",
    "refMin": 0.1,
    "optMin": 0.1,
    "optMax": 99.9,
    "refMax": 99.9,
    "reference": "SK",
    "name_kor": "거대혈소판(%)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Plateletcrit",
    "category": "혈구",
    "unit": "%",
    "refMin": 0.15,
    "optMin": 0.15,
    "optMax": 0.32,
    "refMax": 0.32,
    "reference": "SK",
    "name_kor": "혈소판용적치"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Platelets",
    "category": "혈구",
    "unit": "10^3/µL",
    "refMin": 140,
    "optMin": 155,
    "optMax": 385,
    "refMax": 400,
    "reference": 1,
    "name_kor": "혈소판수",
    "alertMin": 100,
    "alertMessage": "수치가 100 미만이면서 잦은 멍, 무력감 등의 증상이 나타나는 경우에는 상급의료기관 진료를 권고합니다. 30 미만인 경우 응급 진료가 필요합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Potassium",
    "category": "전해질",
    "unit": "mEq/L",
    "refMin": 3.5,
    "optMin": 4,
    "optMax": 4.5,
    "refMax": 5.3,
    "reference": 1,
    "name_kor": "칼륨",
    "alertMin": 3.5,
    "alertMax": 5.5,
    "alertMessage": "신경계 증상을 동반한 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Progesterone",
    "category": "호르몬",
    "sex": "M",
    "unit": "ng/mL",
    "refMin": 0.2,
    "optMin": 1,
    "optMax": 1.2,
    "refMax": 1.3,
    "reference": 1,
    "name_kor": "프로게스테론"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Progesterone",
    "category": "호르몬",
    "sex": "F",
    "unit": "ng/mL",
    "refMin": 2.6,
    "optMin": 18,
    "optMax": 27,
    "refMax": 27,
    "reference": 1,
    "name_kor": "프로게스테론"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Protein - Total",
    "category": "단백질",
    "unit": "g/dL",
    "refMin": 6.1,
    "optMin": 6.9,
    "optMax": 7.4,
    "refMax": 8.1,
    "reference": 1,
    "name_kor": "총단백"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "PSA - Total",
    "category": "전립선",
    "unit": "ng/mL",
    "refMin": 0,
    "optMin": 0,
    "optMax": 2.6,
    "refMax": 4,
    "reference": 1,
    "name_kor": "전립선특이항원"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "RBC",
    "category": "혈구",
    "sex": "M",
    "unit": "10^6/µL",
    "refMin": 4.2,
    "optMin": 4.2,
    "optMax": 4.9,
    "refMax": 5.8,
    "reference": 1,
    "name_kor": "적혈구수"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "RBC",
    "category": "혈구",
    "sex": "F",
    "unit": "10^6/µL",
    "refMin": 3.8,
    "optMin": 3.9,
    "optMax": 4.5,
    "refMax": 5.1,
    "reference": 1,
    "name_kor": "적혈구수"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "RDW",
    "category": "혈구",
    "unit": "%",
    "refMin": 11,
    "optMin": 11.7,
    "optMax": 13,
    "refMax": 15,
    "reference": 1,
    "name_kor": "적혈구분포폭"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "RDW-SD",
    "category": "혈구",
    "unit": "fL",
    "refMin": 25,
    "optMin": 25,
    "optMax": 80,
    "refMax": 80,
    "reference": "SK",
    "name_kor": "적혈구분포(표준편차)"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Reticulocyte count",
    "category": "혈구",
    "unit": "%",
    "refMin": 0.5,
    "optMin": 0.1,
    "optMax": 1.5,
    "refMax": 1.5,
    "reference": 1,
    "name_kor": "망상적혈구수"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Reverse T3",
    "category": "갑상선",
    "unit": "ng/dL",
    "refMin": 8,
    "optMin": 10,
    "optMax": 25,
    "refMax": 25,
    "reference": 1,
    "name_kor": "역T3"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Sex Hormone Binding Globulin",
    "category": "호르몬",
    "sex": "M",
    "unit": "nmol/L",
    "refMin": 10,
    "optMin": 30,
    "optMax": 40,
    "refMax": 50,
    "reference": 1,
    "name_kor": "성호르몬결합글로불린"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Sex Hormone Binding Globulin",
    "category": "호르몬",
    "sex": "F",
    "unit": "nmol/L",
    "refMin": 10,
    "optMin": 30,
    "optMax": 40,
    "refMax": 50,
    "reference": 1,
    "name_kor": "성호르몬결합글로불린"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Sodium",
    "category": "전해질",
    "unit": "mEq/L",
    "refMin": 135,
    "optMin": 135,
    "optMax": 142,
    "refMax": 146,
    "reference": 1,
    "name_kor": "나트륨",
    "alertMin": 135,
    "alertMax": 146,
    "alertMessage": "신경계 증상을 동반한 경우, 상급의료기관 진료를 권고합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Sodium/Potassium Ratio",
    "category": "전해질",
    "unit": "ratio",
    "refMin": 30,
    "optMin": 30,
    "optMax": 35,
    "refMax": 35,
    "reference": 1,
    "name_kor": "나트륨/칼륨 비율"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "T3 Uptake",
    "category": "갑상선",
    "unit": "%",
    "refMin": 22,
    "optMin": 27,
    "optMax": 35,
    "refMax": 37,
    "reference": 1,
    "name_kor": "T3섭취률"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Testosterone - Bioavailable",
    "category": "호르몬",
    "sex": "M",
    "unit": "ng/dL",
    "refMin": 110,
    "optMin": 375,
    "optMax": 575,
    "refMax": 575,
    "reference": 1,
    "name_kor": "생체유용테스토스테론"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Testosterone - Bioavailable",
    "category": "호르몬",
    "sex": "F",
    "unit": "ng/dL",
    "refMin": 0.5,
    "optMin": 5.5,
    "optMax": 8.5,
    "refMax": 8.5,
    "reference": 1,
    "name_kor": "생체유용테스토스테론"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Testosterone - Free",
    "category": "호르몬",
    "sex": "M",
    "unit": "pg/mL",
    "refMin": 46,
    "optMin": 150,
    "optMax": 224,
    "refMax": 224,
    "reference": 1,
    "name_kor": "유리테스토스테론"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Testosterone - Free",
    "category": "호르몬",
    "sex": "F",
    "unit": "pg/mL",
    "refMin": 0.2,
    "optMin": 1,
    "optMax": 2.2,
    "refMax": 5,
    "reference": 1,
    "name_kor": "유리테스토스테론"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Testosterone Total",
    "category": "호르몬",
    "sex": "M",
    "unit": "ng/dL",
    "refMin": 250,
    "optMin": 700,
    "optMax": 900,
    "refMax": 1100,
    "reference": 1,
    "name_kor": "총테스토스테론"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Testosterone Total",
    "category": "호르몬",
    "sex": "F",
    "unit": "ng/dL",
    "refMin": 2,
    "optMin": 35,
    "optMax": 45,
    "refMax": 45,
    "reference": 1,
    "name_kor": "총테스토스테론"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Thyroglobulin Abs",
    "category": "갑상선",
    "unit": "IU/mL",
    "refMin": 0,
    "optMin": 0,
    "optMax": 1,
    "refMax": 1,
    "reference": 1,
    "name_kor": "갑상선 글로불린 항체"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Thyroid Peroxidase (TPO) Abs",
    "category": "갑상선",
    "unit": "IU/mL",
    "refMin": 0,
    "optMin": 0,
    "optMax": 6.8,
    "refMax": 9,
    "reference": 1,
    "name_kor": "갑상선 페록시다아제 항체"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "TIBC",
    "category": "철분",
    "unit": "µg/dL",
    "refMin": 250,
    "optMin": 250,
    "optMax": 350,
    "refMax": 425,
    "reference": 1,
    "name_kor": "총철결합능"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Total T3",
    "category": "갑상선",
    "unit": "ng/dL",
    "refMin": 76,
    "optMin": 90,
    "optMax": 168,
    "refMax": 181,
    "reference": 1,
    "name_kor": "총T3"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Total T4",
    "category": "갑상선",
    "unit": "µg/dL",
    "refMin": 4.5,
    "optMin": 6,
    "optMax": 11.9,
    "refMax": 12,
    "reference": 1,
    "name_kor": "총T4"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Total WBCs",
    "category": "백혈구",
    "unit": "10^3/µL",
    "refMin": 3.8,
    "optMin": 5.5,
    "optMax": 7.5,
    "refMax": 10.8,
    "reference": 1,
    "name_kor": "총백혈구수",
    "alertMax": 11,
    "alertMessage": "발열, 오한 증상이 동반될 수 있습니다. 상급의료기관 진료가 필요합니다."
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Triglyceride/HDL Ratio",
    "category": "지질",
    "unit": "ratio",
    "refMin": 0,
    "optMin": 0,
    "optMax": 2,
    "refMax": 2,
    "reference": 1,
    "name_kor": "중성지방/HDL 비율"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Triglycerides",
    "category": "지질",
    "unit": "mg/dL",
    "refMin": 0,
    "optMin": 70,
    "optMax": 80,
    "refMax": 150,
    "reference": 1,
    "name_kor": "중성지방",
    "alertMax": 500,
    "alertMessage": "500 mg/dL 이상인 경우 상급의료기관 진료를 권고합니다. 특별한 증상이 나타나지 않을 수도 있습니다. "
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "TSH",
    "category": "갑상선",
    "unit": "µU/mL",
    "refMin": 0.4,
    "optMin": 1.3,
    "optMax": 3,
    "refMax": 4.5,
    "reference": 1,
    "name_kor": "갑상선자극호르몬"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Uric Acid",
    "category": "대사",
    "sex": "M",
    "unit": "mg/dL",
    "refMin": 3.5,
    "optMin": 3.5,
    "optMax": 5.9,
    "refMax": 8,
    "reference": 1,
    "name_kor": "요산"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Uric Acid",
    "category": "대사",
    "sex": "F",
    "unit": "mg/dL",
    "refMin": 2.5,
    "optMin": 3,
    "optMax": 5.5,
    "refMax": 7,
    "reference": 1,
    "name_kor": "요산"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Vitamin B12",
    "category": "비타민",
    "unit": "pg/mL",
    "refMin": 200,
    "optMin": 450,
    "optMax": 800,
    "refMax": 1100,
    "reference": 1,
    "name_kor": "비타민B12"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "Vitamin D (25-OH)",
    "category": "비타민",
    "unit": "ng/mL",
    "refMin": 20,
    "optMin": 50,
    "optMax": 100,
    "refMax": 100,
    "reference": 1,
    "name_kor": "비타민D"
  },
  {
    "user_id": "admin",
    "section": "lab",
    "name": "VLDL Cholesterol",
    "category": "지질",
    "unit": "mg/dL",
    "refMin": 0,
    "optMin": 0,
    "optMax": 10,
    "refMax": 29,
    "reference": 1,
    "name_kor": "초저밀도지단백 콜레스테롤"
  }
];

export default items;